### ISSUE TITLE
oftest 1.3: Some tests fail

### ISSUE THREAD

**Issue by msune** [bisdn/xdpd#37]
Check why there is a different behaviour than `ryu` (e.g. DSCP) or simply they are not covered :

```
marc@bisdn-dev:~/BISDN/code/other/oftest$ sudo ./oft --of-version=1.3 --port=6633 --log-file=log_of13.txt flow_mod flow_stats groups match  pktin_match  role_request basic actions
WARNING: No route found for IPv6 destination :: (no default route?)
actions.SetIpv4TTL ... ok
actions.SetVlanPcp ... ok
actions.SetEthDst ... ok
actions.SetIPv6Src ... ok
actions.SetUDPDst ... ok
actions.PushVlanPcp ... ok
actions.SetIPv4Src ... ok
actions.PushVlanVid ... ok
actions.SetEthSrc ... ok
actions.SetIpv4ECN_NonZeroDSCP ... ok
actions.SetIPv6Flabel ... ok
actions.SetIpv4ECN ... ok
actions.SetUDPSrc ... ok
```

```
actions.SetIpv6DSCP_NonZeroECNandFlabel ... FAIL
```

```
actions.PopVlan ... ok
actions.SetIPv6Dst ... ok
actions.SetTCPDst ... ok
actions.SetIpv4Dscp ... ok
actions.OutputMultiple ... ok
actions.SetIpv6ECN ... ok
actions.SetIPv6Flabel_NonZeroDSCPandECN ... ok
actions.DecIpv6HopLimit ... ok
```
```
actions.SetIpv6Dscp ... FAIL
```

```
actions.Output ... ok
actions.SetIpv6HopLimit ... ok
actions.SetIpv4DSCP_NonZeroECN ... ok
actions.SetTCPSrc ... ok
actions.SetVlanVid ... ok
actions.PushVlanVidPcp ... ok
actions.SetIpv6ECN_NonZeroDSCPandFlabel ... ok
actions.PushVlan ... FAIL
actions.SetIPv4Dst ... ok
actions.DecIpv4TTL ... ok
role_request.RoleRequestEqualToSlave ... ok
role_request.RoleRequestSlaveToMaster ... ok
```

```
role_request.RolePermissions ... FAIL
role_request.RoleRequestEqualToMaster ... FAIL
role_request.RoleRequestNochange ... FAIL
role_request.SlaveNoPacketIn ... FAIL
``` 

```
flow_stats.AllFlowStats ... FAIL
flow_stats.CookieFlowStats ... FAIL
```

```
groups.GroupDescStats ... FAIL
```

```
groups.GroupStatsNonexistent ... ok
groups.GroupAddIndirectWeight ... ok
groups.GroupAddInvalidAction ... ok
groups.GroupStatsAll ... ok
groups.GroupModifyEmpty ... ok
groups.SelectFwdSpread ... FAIL
groups.GroupFlowSelect ... ok
groups.GroupStats ... ok

//FAILS here  are unsupported group types by xdpd
groups.SelectFwdSingle ... FAIL
groups.GroupModifyLoop ... FAIL
groups.GroupDeleteAll ... FAIL
groups.GroupAdd ... ok
groups.GroupDeleteNonexisting ... ok
groups.GroupAddSelectNoWeight ... ok
groups.GroupAddMinimumInvalidID ... ok
groups.GroupAddInvalidID ... ok
groups.GroupDeleteExisting ... FAIL
groups.GroupModify ... ok
groups.GroupAddMaxID ... ok
groups.GroupAddIndirectBuckets ... ok
groups.GroupModifyInvalidID ... ok
groups.GroupModifyNonexisting ... ok
groups.GroupAddAllWeight ... ok
groups.SelectFwdEmpty ... FAIL
groups.GroupAddExisting ... ok
basic.GroupDescStats ... ok
```
```
basic.QueueStats ... FAIL
basic.PacketInMiss ... FAIL
```
```
basic.TableStats ... ok
basic.PortConfigMod ... ok
```

```
basic.AsyncConfigGet ... FAIL
```

```
basic.GroupStats ... ok
basic.PortDescStats ... ok
basic.DescStats ... ok
basic.OutputExact ... ok
basic.AggregateStats ... ok
basic.MeterFeaturesStats ... ok
basic.MeterStats ... ok
basic.EchoWithData ... ok
basic.PortStats ... ok
basic.GroupFeaturesStats ... ok
basic.PacketOut ... ok
basic.MeterConfigStats ... ok
basic.PacketInExact ... ok
basic.OutputWildcard ... ok
basic.PacketInWildcard ... ok
basic.DefaultDrop ... ok
basic.Echo ... ok
basic.FlowStats ... ok
basic.FeaturesRequest ... ok
basic.FlowRemoveAll ... ok
flow_mod.Overwrite ... ok
match.IPv4ICMPCode ... ok
match.VlanPCPAnyVID ... ok
match.EthSrcMasked ... ok
match.ArpOp ... ok
match.IPv4DstSubnetMasked ... ok
match.EthSrcMulticast ... ok
match.IPv6DstSubnetMasked ... ok
```

```
match.IPv4TCPDstMasked ... FAIL
```

```
match.IPv4TCPDst ... ok
match.IPv6UDPDst ... ok
match.IPv6Dscp ... ok
match.IPv6TCPDst ... ok
match.IPv4Ecn ... ok
```

```
match.VlanPCPMasked ... FAIL
match.IPv4UDPSrcMasked ... FAIL
```

```
match.IPv6Dst ... ok
match.IPv6ProtoUDP ... ok
match.IPv4ICMPType ... ok
match.IPv4DstMasked ... ok
match.VlanPresent ... ok
match.EthDst ... ok
match.VlanPCP ... ok
match.ArpTPA ... ok
```

```
match.IPv4TCPSrcMasked ... FAIL
```

```
match.IPv6SrcMasked ... ok
match.EthTypeARP ... ok
match.IPv6ICMPCode ... ok
```

```
match.EthTypeNone ... FAIL
```

```
match.IPv4ProtoTCP ... ok
match.IPv4TCPSrc ... ok
match.EthDstBroadcast ... ok
match.EthDstMulticast ... ok
match.VlanVID ... ok
match.IPv6DstMasked ... ok
match.IPv4ProtoICMP ... ok
match.IPv6Ecn ... ok
match.VlanAbsent ... ok
match.EthSrc ... ok
```

```
match.IPv4UDPDstMasked ... FAIL
```

```
match.IPv4ProtoUDP ... ok
match.IPv4SrcSubnetMasked ... ok
match.IPv4UDPDst ... ok
match.IPv4SrcMasked ... ok
match.IPv6ProtoICMP ... ok
match.IPv6UDPSrc ... ok
match.VlanExact ... ok
match.IPv6Src ... ok
match.EthTypeIPv4 ... ok
match.IPv4Dst ... ok
match.IPv6ICMPType ... ok
match.IPv6ProtoTCP ... ok
match.EthDstMasked ... ok
match.InPort ... ok
match.ArpSPA ... ok
match.ArpSPAMasked ... ok
match.IPv4Src ... ok
match.ArpTPAMasked ... ok
match.ArpTPASubnetMasked ... ok
match.IPv6SrcSubnetMasked ... ok
match.EthTypeIPv6 ... ok
match.VlanVIDMasked ... ok
match.IPv4Dscp ... ok
match.IPv6TCPSrc ... ok
match.EthSrcBroadcast ... ok
match.IPv4UDPSrc ... ok
match.ArpSPASubnetMasked ... ok
```

```
pktin_match.VlanAbsent ... FAIL
pktin_match.VlanVid ... FAIL
```

```
======================================================================
FAIL: actions.SetIpv6DSCP_NonZeroECNandFlabel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/actions.py", line 373, in runTest
    self.verify_modify(actions, pkt, exp_pkt)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/actions.py", line 118, in verify_modify
    verify_packets(self, str(exp_pkt), [out_port])
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1682, in verify_packets
    verify_packet(test, pkt, ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1640, in verify_packet
    test.assertTrue(rcv_pkt != None, "Did not receive pkt on %r" % ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Did not receive pkt on 2

======================================================================
FAIL: actions.SetIpv6Dscp
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/actions.py", line 343, in runTest
    self.verify_modify(actions, pkt, exp_pkt)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/actions.py", line 118, in verify_modify
    verify_packets(self, str(exp_pkt), [out_port])
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1682, in verify_packets
    verify_packet(test, pkt, ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1640, in verify_packet
    test.assertTrue(rcv_pkt != None, "Did not receive pkt on %r" % ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Did not receive pkt on 2

======================================================================
FAIL: actions.PushVlan
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/actions.py", line 129, in runTest
    self.verify_modify(actions, pkt, exp_pkt)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/actions.py", line 118, in verify_modify
    verify_packets(self, str(exp_pkt), [out_port])
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1682, in verify_packets
    verify_packet(test, pkt, ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1640, in verify_packet
    test.assertTrue(rcv_pkt != None, "Did not receive pkt on %r" % ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Did not receive pkt on 2

======================================================================
FAIL: role_request.RolePermissions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/role_request.py", line 212, in runTest
    self.verify_permission(True)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/role_request.py", line 254, in verify_permission
    self.assertEquals(err_count, 0, "Expected no errors")
AssertionError: Expected no errors

======================================================================
FAIL: role_request.RoleRequestEqualToMaster
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/role_request.py", line 113, in runTest
    self.assertEqual(role, ofp.OFPCR_ROLE_EQUAL)
AssertionError: 3 != 1

======================================================================
FAIL: role_request.RoleRequestNochange
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/role_request.py", line 53, in runTest
    self.assertEqual(role, ofp.OFPCR_ROLE_EQUAL)
AssertionError: 3 != 1

======================================================================
FAIL: role_request.SlaveNoPacketIn
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/role_request.py", line 285, in runTest
    verify_packet_in(self, pkt, ingress_port, ofp.OFPR_NO_MATCH)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1585, in verify_packet_in
    test.assertTrue(msg is not None, 'Packet in message not received on port %r' % in_port)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Packet in message not received on port 1

======================================================================
FAIL: flow_stats.AllFlowStats
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/flow_stats.py", line 112, in runTest
    self.assertEqual(sorted(entry.instructions), sorted(flow.instructions))
AssertionError: Lists differ: [<loxi.of13.instruction.write_... != [<loxi.of13.instruction.write_...

First differing element 0:
<loxi.of13.instruction.write_actions object at 0x1c94c10>
<loxi.of13.instruction.write_actions object at 0x1c94910>

- [<loxi.of13.instruction.write_actions object at 0x1c94c10>]
?                                                       ^

+ [<loxi.of13.instruction.write_actions object at 0x1c94910>]
?                                                       ^


======================================================================
FAIL: flow_stats.CookieFlowStats
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/flow_stats.py", line 176, in runTest
    self.assertEqual(expected_cookies, received_cookies)
AssertionError: Lists differ: [3722304989] != [0, 3722304989, 24394125756770...

First differing element 0:
3722304989
0

Second list contains 21 additional elements.
First extra element 1:
3722304989

+ [0,
- [3722304989]
? ^          ^

+  3722304989,
? ^          ^

+  243941257567709,
+  453897532596620539,
+  984577451821716361,
+  3157139283506498021,
+  3720976629755749186,
+  6166676430576831018,
+  6792897036723050817,
+  10411714492133508328L,
+  11879938860007223723L,
+  15046755950319947984L,
+  15924971278159633664L,
+  15986934255957377024L,
+  15987178193492639744L,
+  15987178197214944733L,
+  16662928551348110976L,
+  17136651402346799359L,
+  17293822569102704640L,
+  18374686479671623680L,
+  18442240474082181120L,
+  18446462598732840960L]

======================================================================
FAIL: groups.GroupDescStats
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/groups.py", line 636, in runTest
    self.assertEquals(len(stats), 3)
AssertionError: 1 != 3

======================================================================
FAIL: groups.SelectFwdSpread
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/groups.py", line 829, in runTest
    verify_no_errors(self.controller)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1690, in verify_no_errors
    raise AssertionError("unexpected error type=%d code=%d" % (error.err_type, error.code))
AssertionError: unexpected error type=6 code=1

======================================================================
FAIL: groups.SelectFwdSingle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/groups.py", line 793, in runTest
    verify_no_errors(self.controller)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1690, in verify_no_errors
    raise AssertionError("unexpected error type=%d code=%d" % (error.err_type, error.code))
AssertionError: unexpected error type=6 code=1

======================================================================
FAIL: groups.GroupModifyLoop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/groups.py", line 256, in runTest
    self.assertEquals(response.code, ofp.OFPGMFC_LOOP)
AssertionError: 5 != 7

======================================================================
FAIL: groups.GroupDeleteAll
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/groups.py", line 381, in runTest
    stats = get_stats(self, ofp.message.group_desc_stats_request())
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1327, in get_stats
    test.assertTrue(reply is not None, "No response to stats request")
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: No response to stats request

======================================================================
FAIL: groups.GroupDeleteExisting
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/groups.py", line 333, in runTest
    stats = get_stats(self, ofp.message.group_desc_stats_request())
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1327, in get_stats
    test.assertTrue(reply is not None, "No response to stats request")
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: No response to stats request

======================================================================
FAIL: groups.SelectFwdEmpty
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/groups.py", line 762, in runTest
    verify_no_errors(self.controller)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1690, in verify_no_errors
    raise AssertionError("unexpected error type=%d code=%d" % (error.err_type, error.code))
AssertionError: unexpected error type=6 code=1

======================================================================
FAIL: basic.QueueStats
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/basic.py", line 396, in runTest
    stats = get_stats(self, request)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1328, in get_stats
    test.assertEquals(reply.type, msgtype, "Response had unexpected message type")
AssertionError: Response had unexpected message type

======================================================================
FAIL: basic.PacketInMiss
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/basic.py", line 262, in runTest
    verify_packet_in(self, pkt, of_port, ofp.OFPR_NO_MATCH)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1585, in verify_packet_in
    test.assertTrue(msg is not None, 'Packet in message not received on port %r' % in_port)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Packet in message not received on port 1

======================================================================
FAIL: basic.AsyncConfigGet
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/basic.py", line 563, in runTest
    self.assertEquals(response.packet_in_mask_equal_master & 0x07, 0x07)
AssertionError: 3 != 7

======================================================================
FAIL: match.IPv4TCPDstMasked
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 1242, in runTest
    self.verify_match(match, matching, nonmatching)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 77, in verify_match
    verify_packets(self, pktstr, [out_port])
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1682, in verify_packets
    verify_packet(test, pkt, ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1640, in verify_packet
    test.assertTrue(rcv_pkt != None, "Did not receive pkt on %r" % ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Did not receive pkt on 2

======================================================================
FAIL: match.VlanPCPMasked
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 544, in runTest
    self.verify_match(match, matching, nonmatching)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 77, in verify_match
    verify_packets(self, pktstr, [out_port])
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1682, in verify_packets
    verify_packet(test, pkt, ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1640, in verify_packet
    test.assertTrue(rcv_pkt != None, "Did not receive pkt on %r" % ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Did not receive pkt on 2

======================================================================
FAIL: match.IPv4UDPSrcMasked
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 1310, in runTest
    self.verify_match(match, matching, nonmatching)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 77, in verify_match
    verify_packets(self, pktstr, [out_port])
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1682, in verify_packets
    verify_packet(test, pkt, ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1640, in verify_packet
    test.assertTrue(rcv_pkt != None, "Did not receive pkt on %r" % ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Did not receive pkt on 2

======================================================================
FAIL: match.IPv4TCPSrcMasked
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 1174, in runTest
    self.verify_match(match, matching, nonmatching)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 77, in verify_match
    verify_packets(self, pktstr, [out_port])
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1682, in verify_packets
    verify_packet(test, pkt, ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1640, in verify_packet
    test.assertTrue(rcv_pkt != None, "Did not receive pkt on %r" % ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Did not receive pkt on 2

======================================================================
FAIL: match.EthTypeNone
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 425, in runTest
    self.verify_match(match, matching, nonmatching)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 77, in verify_match
    verify_packets(self, pktstr, [out_port])
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1682, in verify_packets
    verify_packet(test, pkt, ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1640, in verify_packet
    test.assertTrue(rcv_pkt != None, "Did not receive pkt on %r" % ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Did not receive pkt on 2

======================================================================
FAIL: match.IPv4UDPDstMasked
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 1378, in runTest
    self.verify_match(match, matching, nonmatching)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/match.py", line 77, in verify_match
    verify_packets(self, pktstr, [out_port])
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1682, in verify_packets
    verify_packet(test, pkt, ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1640, in verify_packet
    test.assertTrue(rcv_pkt != None, "Did not receive pkt on %r" % ofport)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Did not receive pkt on 2

======================================================================
FAIL: pktin_match.VlanAbsent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/pktin_match.py", line 71, in runTest
    optional=True)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/pktin_match.py", line 53, in verify_pktin_match
    msg = verify_packet_in(self, pktstr, in_port, ofp.OFPR_NO_MATCH)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1585, in verify_packet_in
    test.assertTrue(msg is not None, 'Packet in message not received on port %r' % in_port)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Packet in message not received on port 1

======================================================================
FAIL: pktin_match.VlanVid
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/pktin_match.py", line 81, in runTest
    optional=True)
  File "/home/marc/BISDN/code/other/oftest/tests-1.3/pktin_match.py", line 53, in verify_pktin_match
    msg = verify_packet_in(self, pktstr, in_port, ofp.OFPR_NO_MATCH)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/testutils.py", line 1585, in verify_packet_in
    test.assertTrue(msg is not None, 'Packet in message not received on port %r' % in_port)
  File "/home/marc/BISDN/code/other/oftest/src/python/oftest/base_tests.py", line 97, in assertTrue
    unittest.TestCase.assertTrue(self, cond, msg)
AssertionError: Packet in message not received on port 1

----------------------------------------------------------------------
Ran 162 tests in 70.641s

FAILED (failures=27)

```

**Comment by msune** [comment]
Not reproducible anymore
