### ISSUE TITLE
l2hash ma: segfault during l2hash_ht_add_bucket()

### ISSUE THREAD

**Issue by msune** [bisdn/xdpd#71]
First reported by Ferenc Juhasz

```
Starting program: /home/sdn/xdpd-debug/build/src/xdpd/xdpd -c example.cfg -e coremask=0x7
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff42a0700 (LWP 9059)]
[New Thread 0x7ffff3a9f700 (LWP 9060)]
[New Thread 0x7ffff2a6e700 (LWP 9061)]
[New Thread 0x7ffff226d700 (LWP 9062)]
[New Thread 0x7ffef0bff700 (LWP 9063)]
[New Thread 0x7ffeebfff700 (LWP 9064)]
[New Thread 0x7ffeeb7fe700 (LWP 9065)]
[New Thread 0x7ffeeaffd700 (LWP 9066)]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000b71db3 in l2hash_ht_add_bucket (ht=0x23a56a8, hash=65535, bucket=0x29ef910)
    at /home/sdn/xdpd-debug/build/../libs/rofl-datapath/src/rofl/datapath/pipeline/openflow/openflow1x/pipeline/matching_algorithms/l2hash/of1x_l2hash_ma.c:77
77              if(it->entry->priority <= priority)
#0  0x0000000000b71db3 in l2hash_ht_add_bucket (ht=0x23a56a8, hash=65535, bucket=0x29ef910)
    at /home/sdn/xdpd-debug/build/../libs/rofl-datapath/src/rofl/datapath/pipeline/openflow/openflow1x/pipeline/matching_algorithms/l2hash/of1x_l2hash_ma.c:77
#1  0x0000000000b7218e in of1x_add_hook_l2hash (entry=0x29efa60)
    at /home/sdn/xdpd-debug/build/../libs/rofl-datapath/src/rofl/datapath/pipeline/openflow/openflow1x/pipeline/matching_algorithms/l2hash/of1x_l2hash_ma.c:209
#2  0x0000000000b72c38 in of1x_add_flow_entry_table_imp (table=0x20a5290, entry=0x29efa60, check_overlap=false, reset_counts=false, ma_hook_ptr=0xb71f2d <of1x_add_hook_l2hash>)
    at /home/sdn/xdpd-debug/build/../libs/rofl-datapath/src/rofl/datapath/pipeline/openflow/openflow1x/pipeline/matching_algorithms/loop/of1x_loop_ma.c:250
#3  0x0000000000b73085 in __of1x_add_flow_entry_loop (table=0x20a5290, entry=0x29efa60, check_overlap=false, reset_counts=false, ma_hook_ptr=0xb71f2d <of1x_add_hook_l2hash>)
    at /home/sdn/xdpd-debug/build/../libs/rofl-datapath/src/rofl/datapath/pipeline/openflow/openflow1x/pipeline/matching_algorithms/loop/of1x_loop_ma.c:396
#4  0x0000000000b722d3 in of1x_add_flow_entry_l2hash (table=0x20a5290, entry=0x29efa60, check_overlap=false, reset_counts=false)
    at /home/sdn/xdpd-debug/build/../libs/rofl-datapath/src/rofl/datapath/pipeline/openflow/openflow1x/pipeline/matching_algorithms/l2hash/of1x_l2hash_ma.c:258
#5  0x0000000000b6e205 in of1x_add_flow_entry_table (pipeline=0x20a5250, table_id=0, entry=0x7fffffffdb38, check_overlap=false, reset_counts=false)
    at /home/sdn/xdpd-debug/build/../libs/rofl-datapath/src/rofl/datapath/pipeline/openflow/openflow1x/pipeline/of1x_flow_table.c:475
#6  0x0000000000a75e41 in hal_driver_of1x_process_flow_mod_add (dpid=256, table_id=0 '\000', flow_entry=0x7fffffffdb38, buffer_id=4294967295, check_overlap=false, reset_counts=false)
    at ../../../../../../../../../src/xdpd/drivers/gnu_linux_dpdk/src/hal-imp/openflow/openflow1x/of1x_driver.cc:343
#7  0x0000000000b3301c in xdpd::of13_endpoint::flow_mod_add (this=0x26a5840, ctl=..., msg=...) at ../../../../../src/xdpd/openflow/openflow13/of13_endpoint.cc:191
#8  0x0000000000b32c2f in xdpd::of13_endpoint::handle_flow_mod (this=0x26a5840, ctl=..., auxid=..., msg=...) at ../../../../../src/xdpd/openflow/openflow13/of13_endpoint.cc:143
#9  0x0000000000c68876 in rofl::crofctl::flow_mod_rcvd (this=0x26a67a0, auxid=..., msg=0x7ffed8002790) at /home/sdn/xdpd-debug/build/../libs/rofl-common/src/rofl/common/crofctl.cc:1940
#10 0x0000000000c5fbd1 in rofl::crofctl::recv_message (this=0x26a67a0, chan=..., auxid=..., msg=0x7ffed8002790) at /home/sdn/xdpd-debug/build/../libs/rofl-common/src/rofl/common/crofctl.cc:243
#11 0x0000000000c3e7bb in rofl::crofchan::recv_message (this=0x26a6968, conn=..., msg=0x7ffed8002790) at /home/sdn/xdpd-debug/build/../libs/rofl-common/src/rofl/common/crofchan.h:427
#12 0x0000000000c45e8d in rofl::crofconn::send_message_to_env (this=0x26a79e0, msg=0x7ffed8002790) at /home/sdn/xdpd-debug/build/../libs/rofl-common/src/rofl/common/crofconn.cc:786
#13 0x0000000000c464bd in rofl::crofconn::handle_messages (this=0x26a79e0) at /home/sdn/xdpd-debug/build/../libs/rofl-common/src/rofl/common/crofconn.cc:897
#14 0x0000000000c4e0e8 in rofl::crofconn::handle_event (this=0x26a79e0, ev=...) at /home/sdn/xdpd-debug/build/../libs/rofl-common/src/rofl/common/crofconn.h:441
#15 0x0000000000b7f61e in rofl::ciosrv::__handle_event (this=0x26a79e8) at /home/sdn/xdpd-debug/build/../libs/rofl-common/src/rofl/common/ciosrv.cc:84
#16 0x0000000000b809dc in rofl::cioloop::run_on_events (this=0x26a5db0) at /home/sdn/xdpd-debug/build/../libs/rofl-common/src/rofl/common/ciosrv.cc:300
#17 0x0000000000b7fac5 in rofl::cioloop::run_loop (this=0x26a5db0) at /home/sdn/xdpd-debug/build/../libs/rofl-common/src/rofl/common/ciosrv.cc:166
#18 0x0000000000a5f12c in rofl::cioloop::run (this=0x26a5db0) at /home/sdn/xdpd-debug/build/..//libs/rofl-common/src/rofl/common/ciosrv.h:235
#19 0x0000000000a5cbb8 in xdpd::system_manager::init (argc=5, argv=0x7fffffffe568) at ../../../../src/xdpd/management/system_manager.cc:250
#20 0x0000000000a04684 in main (argc=5, argv=0x7fffffffe568) at ../../../src/xdpd/xdpd.cc:25
```

**Comment by msune** [comment]
ROFL-pipeline bug.
